name: ci.yml
on:
  pull_request:
    branches:
      - "dev"

jobs:
  build-test-synfony:
    runs-on: ubuntu-latest
    steps:

      - name: Checkoout
        uses: actions/checkout@v7

      - name: build docker
        run: docker compose -f docker-compose.yml up build

      - name: docker up && install dependencies
        run: |
          docker compose run -rm php_composer install \
          --no-ansi --no-interaction --no-progress --no-scripts --prefer-dist

#      - name: run tests
#        run: docker compose run -rm php_symfony php bin/console test

      - name: stop docker
        if: always()
        run: docker compose down




