name: verysimplecd.yml
on:
  pull_request:
    branches:
      - test

jobs:
  deployed:
    runs-on: ubuntu-latest
    env:
      SSHPASS: ${{ secrets.SSHPASS }}
      SSHUSER: ${{ secrets.SSHUSER }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
